services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_app
    volumes:
      - ./src:/var/www/html
      - composer_home:/var/www/.composer
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres:13
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "hospital"
      POSTGRES_USER: "doctor"
      POSTGRES_PASSWORD: "angina"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - hospital-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doctor -d hospital"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vg_hospital_admin@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "vg_hospital_admin_ps"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/hospital?sslmode=disable"
      DATA_SOURCE_USER: "doctor"
      DATA_SOURCE_PASS: "angina"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      - postgres

volumes:
  hospital-data:
  pgadmin-data:
  composer_home:

networks:
  postgres:
    driver: bridge
